### ISSUE TITLE
cannot log onto server when trying to make an account (for the game)

### ISSUE THREAD

**Issue by aldrichdev** [aldrichdev/Core-Framework#31]
Reported by scquino: 
 
 when I try to create a character for the Web Browser version (I'm on chromebook by the way) it says "Sorry! Couldn't connect you to the servers, check your internet connection" the weird thing is, I have all bars on the internet and it gives me this error.

**Comment by aldrichdev** [comment]
Hi scquino,

You cannot create an account via the game client. You must create your account on the website here: https://www.neatf2p.com/account/game-accounts

**Comment by BeastFable** [comment]
Closing, since this is not an issue we will be solving
