### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by aldrichdev** [aldrichdev/Core-Framework#33]
Reported by baravorik: 
 
 Trying to fish, but it seems shrimp are extremely hard to catch even at level 10 fishing.

**Comment by BeastFable** [comment]
Hey, the fishing rates have been confirmed by Logg (Open RSC developer) to be authentic to how they were in official servers, so this isn't a bug. It is very hard to catch shrimp at low levels - welcome to Classic. :) Closing this.
