### ISSUE TITLE
Banned account after selling item to general store

### ISSUE THREAD

**Issue by aldrichdev** [aldrichdev/Core-Framework#35]
Reported by I Il I I Il: 
 
 Hello, i picked up onions and cabbage near the maze and i go to town to sell it for little gp to buy tools.

suddenly my game log me out and when i try to relog the game say i am permanently banned.

**Comment by BeastFable** [comment]
Looks like your account was created by Overcome, who was banned for botting. Pretty sure you are the same person, so you will stay banned. Closing
